version: '3.1'
services:       # 可设置多个服务
  lau_nginx:        # 服务的名称
    container_name: lauNginx                  # 设置容器名称
    restart: always                          # 表示docker启动时，容器跟着docker一起启动
    image: daocloud.io/library/nginx:1.13.2  # 指定镜像路径,也可直接设置为nginx:latest
    ports:                                   # 端口映射，可设置多个
      - 80:80
    environment:
      TZ: Asia/Shanghai     # 指定时区
    volumes:                # 设置数据卷
      - /opt/lau_docker/lau_nginx/html:/usr/share/nginx/html
     # - /opt/lau_docker/lau_nginx/nginx.conf/:/etc/nginx/nginx.conf
      - /opt/lau_docker/lau_nginx/conf.d/:/etc/nginx/conf.d
      - /opt/lau_docker/lau_nginx/logs:/var/log/nginx
    privileged: true        # 解决nginx的文件调用权限问题
  lau_mysql:
    container_name: lauMysql
    restart: always
    image: daocloud.io/library/mysql:5.7.7
    ports: 
      - 3306:3306
    environment:
      TZ: Asia/Shanghai  
      MYSQL_ROOT_PASSWORD: 123456 
     # MYSQL_DB: myDatabase
    volumes:     
      - /opt/lau_docker/lau_mysql/data:/var/lib/mysql     
      - /opt/lau_docker/lau_mysql/logs:/logs 
      - /opt/lau_docker/lau_mysql/conf:/etc/mysql/conf.d
